services:
  myapp-main:
    image: crubia/qap4:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/qap4
      - spring.datasource.username=root
      - spring.datasource.password=charles123
