spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/qap4
spring.datasource.username=root
spring.datasource.password=charles123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
; if aws worked
; spring.datasource.url=jdbc:mysql://qapdb.ccec7fh1tkqy.us-east-1.rds.amazonaws.com/qap4
; spring.datasource.username=admin
; spring.datasource.password=randompassdrow